name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [workflow_dispatch]
env:
  SOURCES_PATH: .sources
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Checkout pogolitics
        uses: actions/checkout@v3
        with:
          repository: rybick/pogolitics
          path: './.sources'
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List files in the pogolitics repository
        run: |
          ls ${{ github.workspace }}/$SOURCES_PATH
      - name: Build sources
        run: >
             cd "${{ github.workspace }}/$SOURCES_PATH" &&
             ls && 
             ./gradlew clean build &&
             ls
      - name: Copy built application
        run: >
             ls && 
             rm -r ./* &&
             git checkout README.md && echo "#We don't want to lose README" &&
             ls && 
             ls ${{ github.workspace }}/$SOURCES_PATH/ &&
             cp -r ${{ github.workspace }}/$SOURCES_PATH/build/distributions/* ./
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
#      - name: Do some file modifications
#        run: echo 1$(cat tmp1) > tmp1
#      - name: See what's in the file
#        run: cat tmp1
#      - run: git status
#      - uses: EndBug/add-and-commit@v9
#        with:
#          message: update version
      - run: git status
      - run: git log -2